name: lint check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies with retry
        run: |
          for i in 1 2 3; do
            npm ci && break || sleep 10
          done

      - name: Run build
        run: npm run build
